services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
        - app_net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-sv
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-sv:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
        - app_net

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_BUCKETS: "comments,requirements"
    volumes:
      - ./minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - app_net


  postgres:
    image: postgres:latest
    container_name: ticket-db
    restart: always
    environment:
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - app_net


  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    environment:
      EUREKA_URL: "eureka-sv:8761"
      ISSUER_URI: ${ISSUER_URI}
    ports:
      - "443:443"
    volumes:
      - ${GATEWAY_DIR}/api-gateway-0.0.1-SNAPSHOT.jar:/app/app.jar
    networks:
      - app_net
    depends_on:
      - postgres
      - minio


  comment-sv:
    container_name: comment-sv
    build:
      context: ./comment-sv
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      DB_NAME: "comment_db"
      EUREKA_URL: ${EUREKA_URL}
      MINIO_URL: ${MINIO_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: "comments"
      ISSUER_URI: ${ISSUER_URI}
    volumes:
      - ${COMMENT_DIR}/coment-sv-0.0.1-SNAPSHOT.jar:/app/app.jar
    networks:
      - app_net
    depends_on:
      - postgres
      - minio

  eureka-sv:
    container_name: eureka-sv
    build:
      context: ./eureka-sv
    volumes:
      - ${EUREKA_DIR}/eureka-sv-0.0.1-SNAPSHOT.jar:/app/app.jar
    networks:
      - app_net
    depends_on:
      - postgres
      - minio

  requirement-sv:
    container_name: requirement-sv
    build:
      context: ./requirement-sv
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      DB_NAME: "requirement_db"
      EUREKA_URL: ${EUREKA_URL}
      KAFKA_URL: ${KAFKA_URL}
      MINIO_URL: ${MINIO_URL}
      ISSUER_URI: ${ISSUER_URI}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: "requirements"
    volumes:
      - ${REQUIREMENT_DIR}/requirement-sv-0.0.1-SNAPSHOT.jar:/app/app.jar
    networks:
      - app_net
    depends_on:
      - postgres
      - minio

  traceability-sv:
    container_name: traceability-sv
    build:
      context: ./traceability-sv
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      ISSUER_URI: ${ISSUER_URI}
      DB_NAME: "traceability_db"
      EUREKA_URL: ${EUREKA_URL}
      KAFKA_URL: ${KAFKA_URL}
    volumes:
      - ${TRACEABILITY_DIR}/traceability-sv-0.0.1-SNAPSHOT.jar:/app/app.jar
    networks:
      - app_net
    depends_on:
      - postgres
      - minio

  type-sv:
    container_name: type-sv
    build:
      context: ./type-sv
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      DB_NAME: "type_db"
      EUREKA_URL: ${EUREKA_URL}
      ISSUER_URI: ${ISSUER_URI}
    volumes:
      - ${TYPE_DIR}/type-sv-0.0.1-SNAPSHOT.jar:/app/app.jar
    networks:
      - app_net
    depends_on:
      - postgres
      - minio

  user-sv:
    container_name: user-sv
    build:
      context: ./user-sv
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      DB_NAME: "user_db"
      EUREKA_URL: ${EUREKA_URL}
      ISSUER_URI: ${ISSUER_URI}
    volumes:
      - ${USER_DIR}/user-sv-0.0.1-SNAPSHOT.jar:/app/app.jar
    networks:
      - app_net
    depends_on:
      - postgres
      - minio

networks:
    app_net:
        driver: bridge